### ISSUE TITLE
I noticed that the food in the backpack of the Villager Recruits with two-handed weapons was missing

### ISSUE THREAD

**Issue by 1092966399** [Thelnfamous1/Better-Mob-Combat#21] opened 2024-08-09 12:04 UTC
Villager Recruits armed with two-handed weapons (such as Simply Swords-mod) will have all of their backpack food disappear when they need to regain their satiation

**Comment by Thelnfamous1** [comment] 2024-09-12 20:26
Duplicate of #12

**Comment by Thelnfamous1** [comment] 2024-09-12 21:26
Will be fixed in version 1.2.2!

**Closed as completed by Thelnfamous1** 2024-09-12 21:26 UTC
Labels: bug

**Comment by Thelnfamous1** [comment] 2024-09-12 23:57
Some things to keep in mind:

- Recruits will not attempt to eat food if they are holding a 2-handed weapon. This is consistent with players, who cannot eat food in their offhand while holding a 2-handed weapon. This will mean a recruit will never eat while it is equipped with a 2-handed weapon - something to keep in mind when you want to manage their hunger / health.
